title: Home
resources:
  - url: /hacsfiles/lovelace-mushroom/mushroom.js
    type: module
  - url: /hacsfiles/button-card/button-card.js
    type: module
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
views:
  - !include lovelace/views/01_home.yaml
  - !include lovelace/views/02_lighting.yaml
  - !include lovelace/views/03_climate.yaml
  - !include lovelace/views/04_ventilation.yaml
  - !include lovelace/views/05_blinds.yaml
  - !include lovelace/views/06_settings.yaml
